[tool.black]
line-length = 100
target-version = ["py39"]
include = '\.pyi?$'
exclude = '/(\.eggs|\.git|\.hg|\.mypy_cache|\.tox|\.venv|venv|env|_build|buck-out|buildc|dist)/'

[tool.mypy]
plugins = [
    "pydantic.mypy"
]
ignore_missing_imports = true
disallow_untyped_defs = true
warn_unused_ignores = true
warn_return_any = true