import "./globals.css";
import "./_css/base.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { RegisterProvider } from "./_components/register/RegisterProvider";
import { default as AuthProvider } from "./providers/AuthProvider";
import NavBar from "./_components/navbar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RegisterProvider>
        <body className={inter.className}>
          <AuthProvider>{children}</AuthProvider>
          <NavBar />
        </body>
      </RegisterProvider>
    </html>
  );
}
