export const API_ROUTES = {
    auth: {
        login: '/api/auth/login',
        refreshToken: '/api/auth/refresh-token',
        googleLogin: '/api/auth/google-login',
        notificationsPlayerId: '/api/auth/notifications/player-id',
    },
    users: {
        profile: '/api/users/profile',
        profileImage: '/api/users/profile/image',
        activePlans: '/api/users/active-plans',
        byEmail: (email: string) => `/api/users/by-email/${email}`,
        byNumber: (number: string) => `/api/users/by-number/${number}`,
        byId: (id: string) => `/api/users/${id}`,
        sendCode: '/api/users/send-code',
        verifyCode: '/api/users/verify-code',
        updatePassword: '/api/users/update-password',
        resetPassword: '/api/users/reset-password',
        register: '/api/users/register',
        conversations: '/api/users/conversations',
        workoutsProgress: '/api/users/workouts/progress',
        workoutsComplete: '/api/users/workouts/complete',
    },
    workouts: {
        saved: '/api/workouts/saved',
        popular: '/api/workouts/popular',
        library: '/api/workouts/library',
        plans: '/api/workouts/plans',
        oneDay: '/api/workouts/plans/one-day',
        weeklyProgress: '/api/workouts/weekly-progress',
        planById: (id: string) => `/api/workouts/plans/${id}`,
        deleteExercises: (planId: string) => `/api/workouts/plans/${planId}/delete-exercises`,
        updateExercises: (planId: string) => `/api/workouts/plans/${planId}/update-exercises`,
    },
    challenges: {
        list: '/api/challenges/challenges',
        byId: (id: string) => `/api/challenges/challenges/${id}`,
        progress: '/api/challenges/challenges/progress',
        complete: '/api/challenges/challenges/complete',
    },
    chat: '/api/chat',
} as const;
